CREATE TABLE voucher (
    id BIGSERIAL PRIMARY KEY,
    number VARCHAR(64) NOT NULL UNIQUE,
    row_version INT NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
